yarp::sig::SegmentationModuleInterface Class Reference
Interface for module that performs graph-based segmentation.
#include <SegmentationModuleInterface.h>
Public Member Functions
virtual void set_sigma (const double newValue)
Set sigma (smoothing) parameter for the algorithm.
virtual void set_k (const double newValue)
Set k (scale factor for boundary-detection threshold function) parameter for the algorithm.
virtual void set_minRegion (const double newValue)
Set minRegion parameter for the algorithm, i.e., the minimum size of any segmented component.
virtual double get_sigma ()
Get sigma (smoothing) parameter for the algorithm.
virtual double get_k ()
Get k (scale factor for boundary-detection threshold function) parameter for the algorithm.
virtual double get_minRegion ()
Get minRegion parameter for the algorithm, i.e., the minimum size of any segmented component.
virtual std::int32_t get_num_components ()
Get the number of segmented components that have been detected in the last provided image.
virtual std::vector< Pixel > get_component_around (const Pixel &objCenter)
Get the list of pixels corresponding to the component to which a given pixel belongs.
virtual std::vector< std::string > help (const std::string &functionName=`--all`)
bool read (yarp::os::ConnectionReader &connection) override
Detailed Description
Interface for module that performs graph-based segmentation.
Definition at line 27 of file SegmentationModuleInterface.h.
Member Function Documentation
get_component_around()
std::vector< Pixel > yarp::sig::SegmentationModuleInterface::get_component_around (const Pixel & objCenter) [virtual]
Get the list of pixels corresponding to the component to which a given pixel belongs.
Parameters
objCenter a pixel belonging to the region of interest
Returns
list of pixels belonging to the same component as the input pixels
Reimplemented in GBSegmModule.
Definition at line 442 of file SegmentationModuleInterface.cpp.
References get_k(), get_minRegion(), get_num_components(), get_sigma(), set_k(), set_minRegion(), and set_sigma().
{
    SegmentationModuleInterface_get_component_around_helper helper{objCenter};
    if (!yarp().canWrite()) {
        yError("Missing server method '%s'?", "std::vector<Pixel>
       SegmentationModuleInterface::get_component_around(const Pixel& objCenter)");
    }
    bool ok = yarp().write(helper, helper);
    return ok ? SegmentationModuleInterface_get_component_around_helper::s_return_helper :
      std::vector<Pixel>{};
}
get_k()
double yarp::sig::SegmentationModuleInterface::get_k () [virtual]
Get k (scale factor for boundary-detection threshold function) parameter for the algorithm.
Returns
current value for k parameter
Reimplemented in GBSegmModule.
Definition at line 412 of file SegmentationModuleInterface.cpp.
Referenced by get_component_around().
{
    SegmentationModuleInterface_get_k_helper helper{};
    if (!yarp().canWrite()) {
        yError("Missing server method '%s'?", "double SegmentationModuleInterface::get_k()");
    }
    bool ok = yarp().write(helper, helper);
    return ok ? SegmentationModuleInterface_get_k_helper::s_return_helper : double{};
}
get_minRegion()
double yarp::sig::SegmentationModuleInterface::get_minRegion () [virtual]
Get minRegion parameter for the algorithm, i.e., the minimum size of any segmented component.
Returns
current value for minRegion parameter
Reimplemented in GBSegmModule.
Definition at line 422 of file SegmentationModuleInterface.cpp.
Referenced by get_component_around().
{
    SegmentationModuleInterface_get_minRegion_helper helper{};
    if (!yarp().canWrite()) {
        yError("Missing server method '%s'?", "double SegmentationModuleInterface::get_minRegion()");
    }
    bool ok = yarp().write(helper, helper);
    return ok ? SegmentationModuleInterface_get_minRegion_helper::s_return_helper : double{};
}
get_num_components()
std::int32_t yarp::sig::SegmentationModuleInterface::get_num_components () [virtual]
Get the number of segmented components that have been detected in the last provided image.
Returns
number of segmented components
Reimplemented in GBSegmModule.
Definition at line 432 of file SegmentationModuleInterface.cpp.
Referenced by get_component_around().
{
    SegmentationModuleInterface_get_num_components_helper helper{};
    if (!yarp().canWrite()) {
        yError("Missing server method '%s'?", "std::int32_t
       SegmentationModuleInterface::get_num_components()");
    }
    bool ok = yarp().write(helper, helper);
    return ok ? SegmentationModuleInterface_get_num_components_helper::s_return_helper : std::int32_t{};
}
get_sigma()
double yarp::sig::SegmentationModuleInterface::get_sigma () [virtual]
Get sigma (smoothing) parameter for the algorithm.
Returns
current value for sigma parameter
Reimplemented in GBSegmModule.
Definition at line 402 of file SegmentationModuleInterface.cpp.
Referenced by get_component_around().
{
    SegmentationModuleInterface_get_sigma_helper helper{};
    if (!yarp().canWrite()) {
        yError("Missing server method '%s'?", "double SegmentationModuleInterface::get_sigma()");
    }
    bool ok = yarp().write(helper, helper);
    return ok ? SegmentationModuleInterface_get_sigma_helper::s_return_helper : double{};
}
set_k()
void yarp::sig::SegmentationModuleInterface::set_k (const double newValue) [virtual]
Set k (scale factor for boundary-detection threshold function) parameter for the algorithm.
Parameters
newValue new value for k parameter
Reimplemented in GBSegmModule.
Definition at line 384 of file SegmentationModuleInterface.cpp.
Referenced by get_component_around().
{
    SegmentationModuleInterface_set_k_helper helper{newValue};
    if (!yarp().canWrite()) {
        yError("Missing server method '%s'?", "void SegmentationModuleInterface::set_k(const double
       newValue)");
    }
    yarp().write(helper, helper);
}
set_minRegion()
void yarp::sig::SegmentationModuleInterface::set_minRegion (const double newValue) [virtual]
Set minRegion parameter for the algorithm, i.e., the minimum size of any segmented component.
Parameters
newValue new value for minRegion parameter
Reimplemented in GBSegmModule.
Definition at line 393 of file SegmentationModuleInterface.cpp.
Referenced by get_component_around().
{
    SegmentationModuleInterface_set_minRegion_helper helper{newValue};
    if (!yarp().canWrite()) {
        yError("Missing server method '%s'?", "void SegmentationModuleInterface::set_minRegion(const double
       newValue)");
    }
    yarp().write(helper, helper);
}
set_sigma()
void yarp::sig::SegmentationModuleInterface::set_sigma (const double newValue) [virtual]
Set sigma (smoothing) parameter for the algorithm.
Parameters
newValue new value for sigma parameter
Reimplemented in GBSegmModule.
Definition at line 375 of file SegmentationModuleInterface.cpp.
Referenced by get_component_around().
{
    SegmentationModuleInterface_set_sigma_helper helper{newValue};
    if (!yarp().canWrite()) {
        yError("Missing server method '%s'?", "void SegmentationModuleInterface::set_sigma(const double
       newValue)");
    }
    yarp().write(helper, helper);
}
The documentation for this class was generated from the following files:
/home/runner/work/segmentation/segmentation/gh-pages/graphBased/thriftGBseg/include/SegmentationModuleInterface.h
/home/runner/work/segmentation/segmentation/gh-pages/graphBased/thriftGBseg/src/SegmentationModuleInterface.cpp